import {
  acc,
  aim,
  bsh_walls_floors,
  dct,
  diligenceVault,
  educohire,
  entiovi,
  gray,
  matrix,
  maxgen,
  no_logo,
  quantasis,
  sourced,
  spherex,
  true_data,
  uplers,
  yojito,
  sahir_web_solutions_logo,
  walmartglobaltechindia_logo,
  mitchell_martin_logo,
  weareuplers_logo,
  xemplarinsights_logo,
  epam_systems_logo,
  tata_consultancy_services_logo,
  clearspot_ai_logo,
  mankaratechnologies_logo,
  workout_fitness_group_logo,
  cognitivecloud,
  apexdigitalvc_logo,
  virtusa_logo,
  holcim_logo,
  aws,
  searce,
  pivotree,
  instaciti,
  ey,
  virtusa,
  ericsson,
  cgi,
  teglobals,
  otherside,
  cloud9,
  cloudseed,
  impetus,
  logonews,
  skynet,
  bigspire_logo,
  think,
  galgali,
  skyway,
  oceonic,
  koshali,
  systos,
  volts,
  ace,
  globus,
  Gururo,
  explorogent,
  fisheye,
  indeed,
  neo,
  iide,
  zf,
  manitenserv,
  ansrsource,
  gianteagle,
  interniq,
  ispapp,
  freightcom,
  pathfactory,
  altx,
  AXS,
  Aricent,
  only_much_louder_logo,
  Baker_Hughes,
  Media_Guru,
  AABASOFT,
  Flywings_enterprises,
  Thingularity_new,
  MATRIKA_LOGO_R,
  Mirabilis_design_incorporation,
  Techno_Growth_logo,
  Moodys_analytics,
  NLINE_LOGO,
  Xponent_N,
  evry_india_logo,
  finacplus_logo,
  SUN_Mobility,
  corp_id,
  MIT_Logo,
  akkodis,
  AS_Global,
  Acceron,
  hirist_tech_logo,
  hitachi_logo,
  Malabar_group,
  Confidential,
  Makerble,
  lte,
} from "../public/assets/jobs";

export const Jobs = [
  {
    company_name: "Entiovi Technologies",
    job_position: "Fullstack Engineer",
    work_location: "Remote",
    image: entiovi,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3798115354",
    preferred_skills: ["Node.js", "React.js", "Docker", "CI/CD Tools"],
  },
  {
    company_name: "BSH Walls and Floors",
    job_position: "Web Developer",
    work_location: "India(Remote)",
    image: bsh_walls_floors,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3802895780",
    preferred_skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Node.js",
      "Python",
      "React.js",
      "Angular",
      "MySQL",
      "MongoDB",
      "Git",
    ],
  },
  {
    company_name: "METAVERSE VENTURES PRIVATE LIMITED",
    job_position: "Web3 Frontend Developer Remote",
    work_location: "India(Remote)",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3796306144",
    preferred_skills: [
      "Web3",
      "Tailwind CSS",
      "Prisma Photo Editor",
      "Prisma ORM",
      "Non-Fungible Tokens (NFTs)",
      "Metaverse",
      "Decentralized Autonomous Organizations (DAO)",
      "MySDecentralized Applications (DApps)QL",
      "JavaScript Frameworks",
    ],
  },
  {
    company_name: "Uplers",
    job_position: "ReactJS Developer | Frontend Engineer",
    work_location: "India(onsite), Telangana",
    image: uplers,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3798979679",
    preferred_skills: [
      "React Native",
      "JavaScript",
      "NextJs",
      "ReactJs",
      "RestAPI",
    ],
  },
  {
    company_name: "DiligenceVault",
    job_position: "Full Stack Engineer",
    work_location: "India(Remote)",
    image: diligenceVault,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3787766733",
    preferred_skills: [
      " Vue.js",
      "Full-Stack Developmen",
      "NextJs",
      "Back-End Web Development",
      "Angular",
      "Database Development",
    ],
  },
  // Cloud Computing
  {
    company_name: "Yojito Software Private Limited",
    job_position: "Cloud DevOps Engineer",
    work_location: "Pune",
    image: yojito,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3627618630",
    preferred_skills: [
      "SQL",
      "Python ",
      "OpenVMS",
      "Microsoft Azure",
      "Google Cloud Platform (GCP)",
      "Docker",
      "CLI",
    ],
  },
  {
    company_name: "Applied Cloud Computing",
    job_position: "Azure Cloud Engineer",
    work_location: "Mumbai",
    image: acc,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.instahyre.com/job-275072-azure-cloud-engineer-at-applied-cloud-computing-mumbai/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    preferred_skills: [
      "DevOps",
      "AWS ",
      "Cloud Computing",
      "Microsoft Azure",
      "Python",
    ],
  },
  {
    company_name: "Maxgen Technologies Private Limited",
    job_position: "AWS Cloud Engineer",
    work_location: "Mumbai",
    image: maxgen,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.foundit.in/job/aws-cloud-jobs-in-mumbai-maxgen-technologies-private-limited-mumbai-17810918?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    preferred_skills: [
      "DevOps",
      "AWS ",
      "Cloud Computing",
      "Microsoft Azure",
      "Python",
      "Solution Architect",
    ],
  },
  {
    company_name: "Learning360academy",
    job_position: "Cloud computing freelancer trainer",
    work_location: "Thane",
    image: no_logo,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/LY2qHqLSS0B-Lbo92wTyk7YoVTJqEyYtR5skDTRdVZhbX2NlwJ5n5Q",
    preferred_skills: [
      "DevOps",
      "AWS ",
      "Cloud Computing",
      "Microsoft Azure",
      "Amazon RDS",
      "Amazon S3",
      "Amazon EC2",
      "Big query",
      "AI platform",
    ],
  },
  {
    company_name: "Digital Convergence Technologies Inc",
    job_position: "Cloud Architect",
    work_location: "Pune",
    image: dct,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3799267023",
    preferred_skills: [
      "Google Cloud Platform (GCP)",
      "AWS ",
      "Cloud Computing",
      "Microsoft Azure",
      "General Data Protection Regulation (GDPR)",
    ],
  },
  {
    company_name: "Sourced Group an Amdocs Company",
    job_position: "Cloud Data Engineer",
    work_location: "Pune",
    image: sourced,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3775189014",
    preferred_skills: [
      "Data Modeling",
      "AWS ",
      "Data Engineering",
      "Microsoft Azure",
      "Google Cloud Platform (GCP)",
    ],
  },
  {
    company_name: "Quantasis Private Limited",
    job_position: "Cloud Computing Intern",
    work_location: "Mumbai",
    image: quantasis,
    tags: [
      {
        name: "Cloud Computing",
        color: "blue-text-gradient",
      },
    ],
    link: "https://internshala.com/internship/detail/cloud-computing-internship-in-mumbai-at-quantasis-private-limited1704797412",
    preferred_skills: ["DevOps", "AWS ", "Microsoft Azure"],
  },

  // Artifical Intelligence
  {
    company_name: "Matrix Comsec",
    job_position: "Artificial Intelligence Engineer",
    work_location: "Mumbai",
    image: matrix,
    tags: [
      {
        name: "Artificial Intelligence",
        color: "red-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3803148702",
    preferred_skills: [
      "Angular",
      "Artificial Intelligence (AI) ",
      "Computer Vision ",
      "Data Science",
      "Image Processing",
      "Object Detection",
    ],
  },
  {
    company_name: "True Data Software",
    job_position: "Artificial Intelligence Engineer",
    work_location: "Pune",
    image: true_data,
    tags: [
      {
        name: "Artificial Intelligence",
        color: "red-text-gradient",
      },
    ],
    link: "https://careers.truedatasoft.com/public/job-post/7b9095fb-8818-400e-a993-f9d0a2f9afe8/display",
    preferred_skills: [
      "Angular",
      "Artificial Intelligence (AI) ",
      "Computer Vision ",
      "Data Science",
      "Image Processing",
      "Object Detection",
    ],
  },
  {
    company_name: "EducoHire",
    job_position: "Assistant Professor-Artificial Intelligence",
    work_location: "Kopargaon",
    image: educohire,
    tags: [
      {
        name: "Artificial Intelligence",
        color: "red-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3799635251",
    preferred_skills: [
      "Teaching",
      "Artificial Intelligence (AI) ",
      "Problem Solving",
    ],
  },
  {
    company_name: "AIM Research",
    job_position: "Research Analyst - Artificial Intelligence",
    work_location: "Karnataka",
    image: aim,
    tags: [
      {
        name: "Artificial Intelligence",
        color: "red-text-gradient",
      },
    ],
    link: "https://www.shine.com/jobs/research-analyst-artificial-intelligence-permanent/aim-research/13936260?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    preferred_skills: [
      "Research",
      "Artificial Intelligence (AI) ",
      "Data analytics",
      "Anaylsis",
      "Business Strategies",
    ],
  },
  {
    company_name: "Spherex",
    job_position: "Artificial Intelligence Engineer",
    work_location: "Navi Mumbai",
    image: spherex,
    tags: [
      {
        name: "Artificial Intelligence",
        color: "red-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/2QYVf_mz1pJzBfCzAxxtib2PwxJuXh5fdNnNEXpPI_SUdaMoMmb-Xg?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    preferred_skills: [
      "Research",
      "Artificial Intelligence (AI) ",
      "Data analytics",
      "Anaylsis",
      "Business Strategies",
      "TensorFlow",
      "Azure",
      "Computer Science",
      "Pentaho",
      "Kubernetes",
      "PyTorch",
      "NumPy",
      "NoSQL",
      "Git",
      ".NET",
      "Databases",
      "Pandas",
      "Project management",
      "Docker",
      "Machine learning",
      "Natural language processing",
      "Django",
      "OpenCV",
      "Software development",
      "APIs",
      "ETL",
      "Linux",
      "Data science",
      "Keras",
      "Flask",
      "AI",
      "Python",
      "Debugging",
      "MySQL",
    ],
  },
  //Android Developer
  {
    company_name: "Virtusa",
    job_position: "Mobile Engineer",
    work_location: "Andhra Pradesh  ",
    image: virtusa_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3792549971",
    preferred_skills: ["Kotlin"],
  },
  {
    company_name: "Apex Digital",
    job_position: "Game Developer",
    work_location: "India",
    image: apexdigitalvc_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3802250865",
    preferred_skills: [
      "C++",
      "Cyber-security",
      "Engine Development",
      "Game Development",
      "Unreal Engine",
    ],
  },
  {
    company_name: "CognitiveClouds",
    job_position: "Android Developer ",
    work_location: "Bengaluru",
    image: cognitivecloud,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3792947077",
    preferred_skills: ["Android", "Android Development", "Kotlin", "REST APIs"],
  },
  {
    company_name: "FitCraft Technologies Pvt Ltd",
    job_position: "Android Developer",
    work_location: "Noida",
    image: workout_fitness_group_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3558121847",
    preferred_skills: [
      "Android",
      "Android Development",
      "Java",
      "Mobile Application Development",
    ],
  },
  {
    company_name: "Hudini",
    job_position: "Android Developer",
    work_location: "Bangalore",
    image: mankaratechnologies_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3803951321",
    preferred_skills: [
      "C++",
      "Android",
      "Android Development",
      "Android SDK",
      "Kotlin",
      "Java",
    ],
  },
  {
    company_name: "ClearSpot.ai",
    job_position: "Android Developer",
    work_location: "India",
    image: clearspot_ai_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3801429029",
    preferred_skills: [
      "Android",
      "Android Development",
      "AndroidSDK",
      "Application Development",
      "Kotlin",
    ],
  },
  {
    company_name: "Tata Consultancy Services",
    job_position: "Android Developer",
    work_location: "Bengaluru",
    image: tata_consultancy_services_logo,
    tags: [
      {
        name: "Android",
        color: "green-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3799255938",
    preferred_skills: [
      "Android",
      "Android Development",
      "Java",
      "Design Patterns",
      "Kotlin",
    ],
  },
  //ios developer
  {
    company_name: "EPAM Systems",
    job_position: "Lead Software Engineer IOS",
    work_location: "Gurugram",
    image: epam_systems_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3800900843",
    preferred_skills: [
      "Analytical Skills",
      "C",
      "CSS",
      "Python",
      "User Experience",
    ],
  },
  {
    company_name: "Xemplar Insights",
    job_position: "iOS Developer",
    work_location: "Hyderabad",
    image: xemplarinsights_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3801263073",
    preferred_skills: [
      "Android",
      "Android SDK",
      "C",
      "JSON",
      "Flutter",
      "iOS",
      "Swift",
    ],
  },
  {
    company_name: "Uplers",
    job_position: "Lead iOS Engineer | Remote",
    work_location: "Ghaziabad",
    image: weareuplers_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3805010371",
    preferred_skills: [
      "Core Data",
      "Git",
      "C",
      "Swift",
      "UIKit",
      "iOS Development",
    ],
  },
  {
    company_name: "Mitchell Martin Inc.",
    job_position: "SOFTWARE DEVELOPMENT ENGINEER - IOS",
    work_location: "Bengaluru",
    image: mitchell_martin_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3785660511",
    preferred_skills: ["API", "JSON", "REST", "Swift", "UIKit", "iOS"],
  },
  {
    company_name: "Walmart Global Tech India",
    job_position: "SOFTWARE ENGINEER III - iOS",
    work_location: "Bengaluru",
    image: walmartglobaltechindia_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3775181391",
    preferred_skills: ["Rest API", "JSON", "Unit Testing", "XML", "HPC"],
  },
  {
    company_name: "Sahir Web Solutions",
    job_position: "iOS Developer",
    work_location: "Chandigarh",
    image: sahir_web_solutions_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3795856135",
    preferred_skills: [
      "Mobile Application Development",
      "Objective-C",
      "Swift",
      "iOS DEvelopment",
    ],
  },
  {
    company_name: "Holcim",
    job_position: "Mobile (iOS / Android) Engineer",
    work_location: "Navi Mumbai",
    image: holcim_logo,
    tags: [
      {
        name: "IOS Developer",
        color: "purple-text-gradient",
      },
    ],
    link: "https://www.linkedin.com/jobs/view/3797431315",
    preferred_skills: ["Android", "Redux.js", "iOS", "Swift", "OOP"],
  },
  // Cloud Computing
  // Cloud Computing
  {
    company_name: "BigSpire Software",
    job_position: "Associate Cloud Computing Engineer",
    work_location: "Karnataka",
    image: bigspire_logo,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/uWWpjgAl0hgS8L599kCUFmWdFpC1wfyRoT3An2vmmGffT2HxnZNb7g",
    preferred_skills: ["DevOps", "AWS ", "Web Developments in Cloud"],
  },
  {
    company_name: "Tech Gimini",
    job_position: "AWS Cloud Engineer",
    work_location: "Pune",
    image: logonews,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/Acp_EQC7QIbcAduwGZqx9wTxZ1XHcVlx2_pIzGLGkQuvust6e3jqeQ",
    preferred_skills: ["DevOps", "AWS "],
  },
  {
    company_name: "CGI",
    job_position: "Wintel Admin Cloud and Onprem",
    work_location: "Bengaluru",
    image: cgi,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/o8oWC4WO0pgN99UPeqnAGX_7e_kRDLb8dHN2Xbq_6T-pUbyBbwYweg",
    preferred_skills: [
      "DevOps",
      "AWS",
      "VMWare",
      "Virtualization",
      "Operating systems",
      "Azure",
    ],
  },
  {
    company_name: "Ericsson ",
    job_position: "Cloud Engineer",
    work_location: "Bengaluru",
    image: ericsson,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/BTcBKi6pu8BasmgQ0bH8p71VrFGSWShe0iEKat6K2jabO-zR4Hk1Hg",
    preferred_skills: [
      "Docker",
      "AWS",
      "Python",
      "Kubernetes",
      "Jenkins",
      "Azure",
    ],
  },
  {
    company_name: "Virtusa  ",
    job_position: "Cloud Architect Manager-AWS Cloud",
    work_location: "Andhra Pradesh",
    image: virtusa,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/7Lzz85F2Pv00W4Qbyysu06Suce_1nRmHDp8PmZVpGsberjQjSvnJgw",
    preferred_skills: ["AWS", "Azure"],
  },
  {
    company_name: "EY",
    job_position: "Gen AI and Cloud Architect",
    work_location: "Kerala",
    image: ey,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/F3PwJZMjKcWGqo7DWOQRbyy3HVb-8K4E1XpHUbTpSr27KfkzcPz0wg",
    preferred_skills: [
      "AWS",
      "Azure",
      "Natural language processing",
      "DevOps",
      "CI/CD",
      "Image processing",
    ],
  },
  {
    company_name: "Cloudseed Technologies",
    job_position: "Cloud Engineering Track",
    work_location: "India",
    image:  no_logo,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/lp9kFig-xo6o15fth7YpE6SWeU7fx6NvoJZND3Cr0Iv5Grlg2OikhA",
    preferred_skills: [
      "AWS",
      "Azure",
      "Java",
      "DevOps",
      "Virtualization",
      "Python ",
      "Ruby",
    ],
  },
  {
    company_name: "Cloud 9 Infosystems",
    job_position: "Jr Cloud Operations Engineer",
    work_location: "India",
    image: cloud9,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/IuhAV0mgSiITM_IQKoRibyEJ0lrK40EushmaKiP88ukQs9tPgKrfrQ",
    preferred_skills: ["AWS", "Azure"],
  },
  {
    company_name: "InstaCiti.com by Urban Basics",
    job_position: "AWS SES/SNS Engineer",
    work_location: "Bengaluru",
    image: instaciti,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/DeEXk8u8tI618EWtBc_iDT4y9VdVFz8jxzSmkn_kXnWm9JmM8BMO9Q",
    preferred_skills: ["AWS", "Ubuntu"],
  },
  {
    company_name: "Other Side Consulting",
    job_position: "GCP Cloud Data Engineer",
    work_location: "Bengaluru",
    image: otherside,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/NabPKHzL9J21oGzZp7BOgkzWb_gScFOSm1aeDmjIo64XPb64JGzM8g",
    preferred_skills: ["AWS", "Go", "Kubernetes", "Java", "Python", "Linux"],
  },
  {
    company_name: "Impetus Technologies",
    job_position: "AWS Cloud Big Data Architect",
    work_location: "Pune",
    image: impetus,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/NabPKHzL9J21oGzZp7BOgkzWb_gScFOSm1aeDmjIo64XPb64JGzM8g",
    preferred_skills: [
      "AWS",
      "Hadoop",
      "SQL",
      "Java",
      "Apache Hive",
      "DynamoDB",
    ],
  },
  {
    company_name: "Pivotree ",
    job_position: "Production Engineer - Site Reliability Engineer (CLOUD AWS)",
    work_location: "Pune",
    image: pivotree,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/rUJJSX5qwB62_VxatgtANcPAVdJHS9S37YGgBZv2JnZA_WJzBg1jwg",
    preferred_skills: [
      "AWS",
      "Virtualization",
      "Python",
      "Java",
      "Selenium",
      "DynamoDB",
    ],
  },
  {
    company_name: "Searce Technologies",
    job_position: "Cloud Architect",
    work_location: "Pune",
    image: searce,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/jbSngJf_9850W5W612rSe28nSzCQAtnf1G8BWXu5Mk55sTxnJuvGXg",
    preferred_skills: ["AWS", "Google Cloud Platform", "Azure"],
  },
  {
    company_name: "AWS India",
    job_position: "Cloud Support Engineer (Analytics)",
    work_location: "Bengaluru",
    image: aws,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/swUQNM3fqm9P6kuZ0aI6JdM16n2Eve7WbC1kLuamOp-T0HMw8_DX4A",
    preferred_skills: [
      "AWS",
      "Google Cloud Platform",
      "Azure",
      ".NET",
      "MySQL",
    ],
  },
  {
    company_name: "Teleglobal International",
    job_position: "AWS Cloud Engineer",
    work_location: "Bengaluru",
    image: no_logo,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/JrJA3T-bAW9n8K4IwaHr00Q6JO8Nq10IcCG07oGLm2NDSL6AQS8ovA",
    preferred_skills: [
      "AWS",
      "Google Cloud Platform",
      "Azure",
      ".NET",
      "MySQL",
    ],
  },
  {
    company_name: "Skynet Secure Solutions",
    job_position: "Cloud Computing Trainer & Developer",
    work_location: "Mumbai",
    image: skynet,
    tags: [
      {
        name: "Cloud Computing",
        color: "-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/p9ixDnigvhBnV7CdgamLmxzSBUtLrUJi6uO2_NkiJha2nR1MD16Nxw",
    preferred_skills: [
      "AWS",
      "Google Cloud Platform",
      "Azure",
      ".NET",
      "MySQL",
    ],
  },

  // Web Development
  {
    company_name: "PathFactory",
    job_position: "Associate Web Developer",
    work_location: "Remote",
    image: pathfactory,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/H_JPr-BgLT9106_SRd3o1HWmeQOfFjVxwcWj-rkknksIh1sun77Ptg",
    preferred_skills: [
      "Web design",
      "Adobe Photoshop",
      "CSS",
      "Bootstrap",
      "Web development",
      "Adobe Illustrator",
      "HTML5",
    ],
  },
  {
    company_name: "Freightcom",
    job_position: "Angular Developer",
    work_location: "Remote",
    image: freightcom,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/vUZ2wzs_4CPOtXzPzkoRaRBB-HnISzF2lUK49GG3_wPvWZQ3GX1nDQ",
    preferred_skills: [
      "Web design",
      "SCSS",
      "CSS",
      "Bootstrap",
      "Software development",
      "TypeScript",
      "HTML5",
      "JavaScript",
    ],
  },
  {
    company_name: "ISPApp",
    job_position: "Junior Web Developer",
    work_location: "Remote",
    image: ispapp,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/7iWuddeiDbUcey5l5UbwpRDpknrTy-Myi5uz5g2enZuCfI4Pql_CEw",
    preferred_skills: ["Go", "Node.js", "React", "AWS", "JavaScript"],
  },
  {
    company_name: "InternIQ",
    job_position: "Python Developer Intern",
    work_location: "Remote",
    image: interniq,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/rvJOVGqfrGiqESrphohOlUyZsPbh5Y2We5_91kZ8AnAKFILCE4-PKw",
    preferred_skills: ["NumPy", "Pandas", "Python"],
  },
  {
    company_name: "NIK ENTERPRISES PVT.LTD",
    job_position: "Web Developer",
    work_location: "Remote",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/DaDZwFLNwVnKD0pgUcpicJVC-v2shvrr1b3i2_tvP8QEpN5fG54rGw",
    preferred_skills: ["React", "Git", "PHP", "React Native", "JavaScript"],
  },
  {
    company_name: "Giant Eagle GCC",
    job_position: "Lead Developer Backend",
    work_location: "Karnataka",
    image: gianteagle,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/6Ia2p7wt6OS78yIZy1_OBW2moBtQSpwsl4B2eAo3nf4jP7TPV-P9mg",
    preferred_skills: [
      "Azure",
      "Node.js",
      "AWS",
      "REST",
      "Angular",
      "APIs",
      "MySQL",
      "Ruby on Rails",
    ],
  },
  {
    company_name: "ansrsource",
    job_position: "Internship - HTML Developer",
    work_location: "Remote",
    image: ansrsource,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/XcXU3osM_DqDDu3tFCu6lLbkXmPzqb2cVNLZWXKqj0WHjwuQIjo5xQ",
    preferred_skills: [
      "CSS",
      "Adobe Dreamweaver",
      "JavaScript",
      "jQuery",
      "Angular",
      "HTML5",
    ],
  },
  {
    company_name: "Maniten Services",
    job_position: "Web Development Internship",
    work_location: "India",
    image: manitenserv,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/XOtSKqJ09-iU_6EkIyS8IvcGCIEgLzK4QfK9b9idNq8GIonUWNXaeQ",
    preferred_skills: [
      "CSS",
      "Bootstrap",
      "JavaScript",
      "jQuery",
      "PHP",
      "HTML5",
      "MySQL",
    ],
  },
  {
    company_name: "ZF",
    job_position: "UI Platform Engineer (Front End Developer)",
    work_location: "Bengaluru",
    image: zf,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/tWElcHZtuT2o_em7_2kA0Mhlj1cpQ_GjaNA5-h2mWYRTGImfM_P_LQ",
    preferred_skills: [
      "CSS",
      "Bootstrap",
      "JavaScript",
      "UI",
      "React Native",
      "HTML5",
      "React",
      "TypeScript",
    ],
  },
  {
    company_name: "Indian Institute of Digital Education Pvt Ltd",
    job_position: "Web Developer - Remote",
    work_location: "Remote",
    image: iide,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/i2o5AIfihc32jARCgNfQX-1z-I0q4-p86-fzjG9fYIkk4of9_RLxXw",
    preferred_skills: [
      "CSS",
      "WordPress",
      "JavaScript",
      "SEO",
      "jQuery",
      "PHP",
    ],
  },
  {
    company_name: "Neo Software Solutions",
    job_position: "Web Developer",
    work_location: "Remote",
    image: neo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/uK44iwLegjrS02vzwf8IGrSSchXh29cF-piGdvIJ-ldC8uTRpNmptA",
    preferred_skills: [
      "CSS",
      "Software deployment",
      "Django",
      "React Native",
      "HTML5",
      "MySQL",
    ],
  },
  {
    company_name: "indeed",
    job_position: "Software Engineer II",
    work_location: "Hyderabad",
    image: indeed,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/txBngi_BdgtfHr5WepzafiAZOxkEJqE7b7xwnUImOwr1p_tU5BkQmQ",
    preferred_skills: [
      "Data modeling",
      "React",
      "Full-stack development",
      "Java",
      "JavaScript",
      "MySQL",
      "Angular",
    ],
  },
  {
    company_name: "Fish Eye Advertising",
    job_position: "Web Developer",
    work_location: "Remote",
    image: fisheye,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/6WKmduYtwigqGMQuAv1XwDKEWXPSW3f5_FrZ-Tnvxx2KQErtLSCK9Q",
    preferred_skills: ["CSS", "WordPress", "XML", "HTML5", "JavaScript"],
  },
  {
    company_name: "Explorogent International Services Private Limited",
    job_position: "Web Development Intern",
    work_location: "Remote",
    image: explorogent,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/viZHraUFLgwN1LptqQk1MkVIquc76bEVh5j8m9f2QchTHKPRT-iMIw",
    preferred_skills: ["CSS", "React", "HTML5", "JavaScript"],
  },
  {
    company_name: "Upakarna",
    job_position: "Web Development Intern",
    work_location: "Mumbai",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/aIDa4QMEI0RSnQNTUqayB5Jt2GyL6PZk4FDHf0MyNKZ61I4CG0F4xA",
    preferred_skills: ["CSS", "Git", "SEO", "JavaScript", "APIs", "HTML5"],
  },
  {
    company_name: "Gururo",
    job_position: "Web Development",
    work_location: "Mumbai",
    image: Gururo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/amrglxoRDv_fa7JGRI1kzfiutWpy8hmAqiFMV5TWZQGRF5ZGP72aNg",
    preferred_skills: ["WordPress"],
  },
  {
    company_name: "Globus family of brands India Pvt Ltd",
    job_position: "Web Designer",
    work_location: "Bengaluru",
    image: globus,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/0oO1iYMJljqvFHd5VtMpbkEzlASCjhTwPWQuvpCfv9OOJkub1ipwvA",
    preferred_skills: [
      "FTP",
      "CSS",
      "Bootstrap",
      "PHP",
      "MySQL",
      "HTML5",
      "JavaScript",
      "Adobe Creative Suite",
    ],
  },
  {
    company_name: "Ace Advertising Solutions",
    job_position: "Web Designer",
    work_location: "Bengaluru",
    image: ace,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/J3E3SMJ3kOkX4pizsumeEeyO50chbPw_loZtIUARbv4uzXA2fb2sVw",
    preferred_skills: [
      "APIs",
      "CSS",
      "jQuery",
      "Joomla",
      "MySQL",
      "HTML5",
      "JavaScript",
      "Web development",
    ],
  },
  {
    company_name: "Volts Consulting",
    job_position: "Web Designer",
    work_location: "Bengaluru",
    image: volts,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/6SkNqSCAJJl1RanXr4TfxfTvkxoGR0ERz3MObXwNNcnQ7TGgdwudOA",
    preferred_skills: [
      "CRM software",
      "CSS",
      "WordPress",
      "PHP",
      "HTML5",
      "JavaScript",
      "Web development",
    ],
  },
  {
    company_name: "KOGNICLOUD TECHNOLOGY",
    job_position: "Java Software Engineer",
    work_location: "Chhattisgarh",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/9wbTFYD42c-Bq3ElttqVPR1SruM_BGGE5zg26tUnZnd8S15zKj4dEA",
    preferred_skills: [
      "Spring Boot",
      "CI/CD",
      "Azure",
      "JUnit",
      "Kubernetes",
      "NoSQL",
      "Git",
      "Google Cloud Platform",
      "J2EE",
      "Java",
      "AWS",
      "Docker",
      "Splunk",
      "RabbitMQ",
    ],
  },
  {
    company_name: "SyStos",
    job_position: "Web Development Internship",
    work_location: "Indore",
    image: systos,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/zJYnHYlOrAOmexnNyPGQVXWS2jr1KMBrTOEOOaYlamvcKoRljY4m6Q",
    preferred_skills: [
      "Spring Boot",
      "CI/CD",
      "Azure",
      "JUnit",
      "Kubernetes",
      "NoSQL",
      "Git",
      "Google Cloud Platform",
      "J2EE",
      "Java",
      "AWS",
      "Docker",
      "Splunk",
      "RabbitMQ",
    ],
  },
  {
    company_name: "Koshali Arts & Crafts Enterprise",
    job_position: "Java Software Engineer",
    work_location: "Raipur",
    image: koshali,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/DT594sb7ZNg8lCAYBcMV1Hb60TkI51buBHCGOH1oBDxh9c1SeUApMA",
    preferred_skills: [
      "Spring Boot",
      "CI/CD",
      "Azure",
      "JUnit",
      "Kubernetes",
      "NoSQL",
      "Git",
      "Google Cloud Platform",
      "J2EE",
      "Java",
      "AWS",
      "Docker",
      "Splunk",
      "RabbitMQ",
    ],
  },
  {
    company_name: "SVPNC TECHNOLOGIES",
    job_position: "Salesforce Developer",
    work_location: "Raipur",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/5wY5dpCowix25kovqlyxiWaRSa4GqsOKy85_-yJt2qjWNMTeD2NuQg",
    preferred_skills: [
      "CSS",
      "XML",
      "Salesforce",
      "JavaScript",
      "Pardot",
      "APIs",
      "Agile",
      "JSON",
      "HTML5",
    ],
  },
  {
    company_name: "Thermo Fisher Scientific",
    job_position: "Engineer III, Software",
    work_location: "Bengaluru",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/4ADouw0CaxP2j8srT6t7xfkG_VnTzsUdd_k1-AY0bOd0scTKG1z30A",
    preferred_skills: [
      "AJAX",
      "CI/CD",
      "CSS",
      "Oracle",
      "Kubernetes",
      "NoSQL",
      "Git",
      "Bootstrap",
      "JavaScript",
      "HTML5",
      "MySQL",
      "Spring",
    ],
  },
  {
    company_name: "Oceonic it solution private limited",
    job_position: "Web design & Development Internship",
    work_location: "Varanasi",
    image: oceonic,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/DT594sb7ZNg8lCAYBcMV1Hb60TkI51buBHCGOH1oBDxh9c1SeUApMA",
    preferred_skills: ["CSS", "HTML5"],
  },
  {
    company_name: "Skyway Coach Lines",
    job_position: "Full-Stack Developer (Java/PHP) with DevOps Expertise",
    work_location: "Remote",
    image: skyway,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/T95wC94E4uKHO3MrWC3UymbXqe8dCY1f-LFtrFSLEalQS1vt6Mo_eg",
    preferred_skills: [
      "CSS",
      "HTML5",
      "SQL",
      "Java",
      "PHP",
      "DevOps",
      "REST",
      "Angular",
      "APIs",
      "Jenkins",
      "Spring",
    ],
  },
  {
    company_name: "Galagali Multimedia",
    job_position: "HTML Developer Intern",
    work_location: "Thane",
    image: galgali,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/oYI4I_1pUY81-Ru5L7zcwMxuqKcKf4Ffsa9249LZwSxT08ycMD8slg",
    preferred_skills: ["Adobe Dreamweaver", "Adobe Photoshop", "CSS", "HTML5"],
  },
  {
    company_name: "Think Huge Ltd",
    job_position: "Backend Software Developer (PHP/Python)",
    work_location: "Remote",
    image: think,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/oYI4I_1pUY81-Ru5L7zcwMxuqKcKf4Ffsa9249LZwSxT08ycMD8slg",
    preferred_skills: [
      "Laravel",
      "Git",
      "Bash",
      "PHP",
      "Virtualization",
      "Perl",
      "GitHub",
      "PHP",
      "MySQL",
    ],
  },
  {
    company_name: "LFE",
    job_position: "PHP Wordpress Developer",
    work_location: "Bengaluru",
    image: no_logo,
    tags: [
      {
        name: "Web Developer",
        color: "pink-text-gradient",
      },
    ],
    link: "https://www.simplyhired.co.in/job/oYI4I_1pUY81-Ru5L7zcwMxuqKcKf4Ffsa9249LZwSxT08ycMD8slg",
    preferred_skills: [
      "Adobe Photoshop",
      "CSS",
      "Bootstrap",
      "WordPress",
      "PHP",
      "JavaScript",
      "APIs",
      "Linux",
      "JSON",
      "jQuery",
    ],
  },
  // Software Testing
  {
    company_name: "LTE Techsoft",
    job_position: "Software Testing",
    work_location: "Secunderabad, Telangana",
    image: lte,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=66991391&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Selenium WebDriver, Java, Selenium Grid, Jenkins"],
  },
  {
    company_name: "Makerble",
    job_position: "Manual Software Testing",
    work_location: "India",
    image: no_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/talentApply?id=f4b9c4a32dbe&apply_type=talentApply&k=Software%2BTesting&l=India&route=applyQuestions&panel=apply_standard_questions",
    preferred_skills: ["Adobe Suite, Front-end development, Design system tools, Motion design tools"],
  },
  {
    company_name: "Confidential",
    job_position: "Engineer Software Testing",
    work_location: "Bangalore, Karnataka",
    image: Confidential,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=67402723&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Web Application, Mobile Application, IOT"],
  },
  {
    company_name: "Malabar Group",
    job_position: "Executive - Software Testing",
    work_location: "Kozhikode, Kerala",
    image: Malabar_group,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&pagination=1&id=eedfbad51197&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=71ef1fc5b0ec452ff8d91a4f&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["communication"],
  },



  {
    company_name: "Hitachi Energy",
    job_position: "Software Testing Engineer",
    work_location: "Chennai, Tamil Nadu",
    image: hitachi_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72622031&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["quality Assurance, Test Analyst"],
  },



  {
    company_name: "Annex India",
    job_position: "Software Testing Engineer",
    work_location: "Vadodara, Gujarat",
    image: hirist_tech_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&pagination=1&id=d30084328161&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=71ef1fc5b0ec452ff8d91a4f&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["Automation Testing, Feasibility Testing"],
  },
  {
    company_name: "Acceron",
    job_position: "software testing",
    work_location: "India",
    image: Acceron,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&pagination=1&id=b1bc0da0cc13&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=71ef1fc5b0ec452ff8d91a4f&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["validation,defect tracking,automated testing,manual testing,software testing"],
  },
  {
    company_name: "A S Global Solution",
    job_position: "Software Testing",
    work_location: "Telangana, India",
    image: AS_Global,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=49616283&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["good technical skills"],
  },




  {
    company_name: "Akkodis",
    job_position: "Software Testing",
    work_location: "Bangalore, Karnataka",
    image: akkodis,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72081655&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["basic C and Python, A-SPICE, JIRA ticketing"],
  },
 {
    company_name: "MigrationIT",
    job_position: "Sr. Software Testing Engineer",
    work_location: "India",
    image: MIT_Logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/talentApply?id=8afc71c20199&apply_type=talentApply&k=Software%2BTesting&l=India&route=applyQuestions&panel=apply_standard_questions",
    preferred_skills: ["Java, C#, SQL, "],
  }, {
    company_name: "Hitachi Ltd.",
    job_position: "Software Testing Engineer",
    work_location: "Chennai, Tamil Nadu",
    image: corp_id,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72627035&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Design testing, Azure DevOps"],
  },


  {
    company_name: "SUN Mobility",
    job_position: "Software Testing Specialist",
    work_location: "Bangalore, Karnataka",
    image: SUN_Mobility,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&pagination=1&id=a2915e2f9fcd&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=71ef1fc5b0ec452ff8d91a4f&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["software testing, Project Managment"],
  }, {
    company_name: "FinacPlus",
    job_position: "Software Testing Engineer (Fresher)",
    work_location: "Telangana, India",
    image: finacplus_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72899387&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["SQL, manage defects, back-end testing"],
  }, {
    company_name: "EVRY India",
    job_position: "Software Engineer- Testing",
    work_location: "Bangalore, Karnataka",
    image: no_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=66382655&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Testing Fundamentals, Selenium with C#, Selenium with Java"],
  }, {
    company_name: "Xponent N",
    job_position: "Software Testing - Trainer",
    work_location: "Thane, Maharashtra",
    image: Xponent_N,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72181443&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Handling queries, Performance Testing"],
  }, {
    company_name: "Nlineaxis",
    job_position: "Software Testing Lead - Manual/Automation Testing",
    work_location: "Jaipur, Rajasthan",
    image: NLINE_LOGO,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&pagination=1&id=ecedd425b8a4&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=71ef1fc5b0ec452ff8d91a4f&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["Running Test Cases, Regression Testing"],
  }, {
    company_name: "Moodys Analytics",
    job_position: "Software Engineer Performance Testing",
    work_location: "Gurugram, Haryana",
    image: Moodys_analytics,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=69056875&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Performance Testing"],
  }, {
    company_name: "Technogrowth Software Solutions Private Limited",
    job_position: "Software Testing Engineer",
    work_location: "Pune, Maharashtra",
    image: Techno_Growth_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=65700865&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["automation testing, Agile development"],
  }, {
    company_name: "Mirabilis Design Incorporation",
    job_position: "Software Testing Engineer",
    work_location: "Chennai, Tamil Nadu",
    image: Mirabilis_design_incorporation,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=66227495&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Basic Knowledge of Java and Python"],
  }, {
    company_name: "Matrika Engineering Works",
    job_position: "Software Testing Engineer",
    work_location: "Bangalore, Karnataka",
    image: MATRIKA_LOGO_R,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=66991969&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: [".NET, J2EE, Regression / Functional Tests"],
  }, {
    company_name: "Thingularity",
    job_position: "Software Testing Engineer",
    work_location: "Bangalore, Karnataka",
    image: Thingularity_new,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&p=2&pagination=2&id=9dee54cf4d59&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=8aaa3628fe560ca187a1bd4c&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["regressive system testing"],
  }, {
    company_name: "Flywings enterprises",
    job_position: "Software Testing Executive",
    work_location: "India",
    image: Flywings_enterprises,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.timesjobs.com/candidate/JobDetailView.html?from=submit&adId=69144234&bc=EXT&sequence=0&counter=1&utm_source=Talent&utm_medium=referral&utm_campaign=Talent_Feed&siteparams=talent_feed&fnm=talent_feed",
    preferred_skills: ["Testing Fundamentals, Software Testing, Selenium Testing, Web Drive , Agile Scrum Testing, Api Testing, SQL Testing."],
  }, {
    company_name: "AABASOFT",
    job_position: "INTERNSHIP - SOFTWARE TESTING",
    work_location: "India",
    image: no_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.timesjobs.com/candidate/JobDetailView.html?from=submit&adId=69296648&bc=EXT&sequence=0&counter=1&utm_source=Talent&utm_medium=referral&utm_campaign=Talent_Feed&siteparams=talent_feed&fnm=talent_feed",
    preferred_skills: ["Manual testing, Software Testing, Troubleshooting"],
  }, {
    company_name: "New Media Guru India Pvt Ltd",
    job_position: "Software Testing Analyst",
    work_location: "India",
    image: Media_Guru,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.timesjobs.com/candidate/JobDetailView.html?from=submit&adId=65843388&bc=EXT&sequence=0&counter=1&utm_source=Talent&utm_medium=referral&utm_campaign=Talent_Feed&siteparams=talent_feed&fnm=talent_feed",
    preferred_skills: ["Manual and automated testing, QTP, Selenium, Load Runner"],
  }, {
    company_name: "Baker Hughes",
    job_position: "Software Testing Engineer",
    work_location: "Mumbai, Maharashtra",
    image: Baker_Hughes,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=62972691&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["quality requirement, FOE"],
  }, {
    company_name: "Only Much Louder",
    job_position: "Software Development Engineer",
    work_location: "Bangalore, Karnataka",
    image: only_much_louder_logo,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&p=2&pagination=2&id=79860629394e&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=8aaa3628fe560ca187a1bd4c&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["Quality Assurance, building SAAS"],
  }, {
    company_name: "Aricent",
    job_position: "Project Management",
    work_location: "Madhya Pradesh, India",
    image: Aricent,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.hirist.com/j/project-management-software-testing-2-8-yrs-1284426.html?ref=neuvoo&utm_source=neuvoo",
    preferred_skills: ["manual and automated testing"],
  }, {
    company_name: "AXS Solutions and Consulting Pvt. Ltd.",
    job_position: "Software Tester",
    work_location: "Navi Mumbai, Maharashtra",
    image: AXS,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://in.talent.com/redirect?l=INDIA&p=2&pagination=2&id=1635c95ecef3&ss=1&testid=relevancyRequirementsV3&eligible=yes&context=serp&initiator=software+testing&search_id=8aaa3628fe560ca187a1bd4c&nb=true&action=f-link&country=in&targetSource=0&pagetype=serp",
    preferred_skills: ["test cases and test data, SDLC"],
  }, {
    company_name: "altx",
    job_position: "Software testing and customer support",
    work_location: "Bangalore, Karnataka",
    image: altx,
    tags: [
      {
        name: "Software Testing",
        color: "light-green-text-gradient",
      },
    ],
    link: "https://www.foundit.in/seeker/single-page-registration?from=Apr16_JobAggregator_neuvoo.com&spl=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&gd=1&jobid=72893333&action=apply&utm_campaign=IN_paid_job_boards_acq_affiliates_Apr16_JobAggregator_neuvoo.com_Feed&utm_medium=affiliates&utm_source=Apr16_JobAggregator_neuvoo.com",
    preferred_skills: ["Test Cases, Manual Testing"],
  }

];
